version: 2

project_name: jig

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: jig
    main: ./cmd/skills
    binary: jig
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/takoeight0821/skills/jig/pkg/version.Version={{.Version}}
      - -X github.com/takoeight0821/skills/jig/pkg/version.Commit={{.ShortCommit}}
      - -X github.com/takoeight0821/skills/jig/pkg/version.Date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: takoeight0821
    name: skills
  draft: false
  prerelease: auto
